### PR TITLE
Remove broken scopes

### LINKED ISSUE #44: Linting produces false positives with .erb files
When html-linter tries to lint `erb` files, it incorrectly complains about `<%` and `<%=`.

captura de ecra de 2015-10-28 16 15 16

It will also complain that the file should have a doctype, which obviously isn't needed in an `erb` view or partial.

### LINKED ISSUE #45: Unexpected token m
I'm getting the following error: 

```
SyntaxError: Unexpected token m
  at Object.parse (native)
  at /Users/hugo/.atom/packages/linter-htmlhint/lib/init.coffee:41:32
  at process._tickCallback (node.js:365:9)
```

Atom version: 1.0.19

### LINKED ISSUE #47: It should not lint .hbs files
How can I stop it from trying to lint .hbs files? It completely gets it wrong. Plus I have the handlebars linter for that.

### LINKED ISSUE #50: Unexpected end of file
This error was showed after I created a HTML file with markdown-preview.

```
SyntaxError: Unexpected end of input
  at Object.parse (native)
  at D:\Users\%username%\.atom\packages\linter-htmlhint\lib\init.coffee:41:32
  at process._tickCallback (node.js:365:9)
```

Atom 1.1.0
Windows 7

### PR DESCRIPTION
**Pull request by Arcanemagus**
Removes a bunch of scopes that this linter doesn't properly handle.

Fixes #44.
Fixes #45.
Fixes #47.
Fixes #50.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
@johnwebbcole Does htmlhint _actually_ handle anything other than basic HTML? I'll be merging this in a few hours if I don't hear from you since as it currently stands this is just breaking things for people.

**Comment by johnwebbcole** [comment]
Your removing a lot is scopes that I use.

**Comment by Arcanemagus** [comment]
Does `htmlhint` actually properly handle those? Those are all templated scopes and from the looks of it `htmlhint` is only intended for pure HTML.

**Comment by Arcanemagus** [comment]
@johnwebbcole almost half of the open issues are related to this linter linting things that it shouldn't be, are any of the scopes that are removed by this actually handled by `htmlhint`?

**Comment by Arcanemagus** [comment]
Did some testing/research:

Scope | Supported
-------- | -------------
`text.html.angular` | No
`text.html.erb` | [No](https://github.com/AtomLinter/linter-htmlhint/issues/44)
`text.html.gohtml` | No
`text.html.jsp` | No
`text.html.mustache` | Yes?
`text.html.handlebars` | [No](https://github.com/AtomLinter/linter-htmlhint/issues/47)
`text.html.ruby` | No

I might consider `text.html.angular` as it seems that it is somewhat "valid" HTML, it's main issue being custom attributes on the elements which isn't allowed strictly following the spec. The fact that `htmlhint` doesn't know to check for that is a ding against it, but it means that files of that scope might work here. The same reasoning goes for Mustache.js templates: They are close enough to real HTML that I think they could probably stay for now if absolutely necessary.

The issue with both of them though is that if `htmlhint` is ever improved those will start becoming invalid as it is _only_ designed for HTML.

Do you want me to add those two scopes back in pending future removal when `htmlhint` improves, or just remove them now so the users of this aren't confused later?

**Comment by johnwebbcole** [comment]
I'm using angular, handlebars, and mustache every day.  And it works great.  Many of the errors reported don't have to do with htmlhint, but the linter helpers.

**Comment by Arcanemagus** [comment]
@johnwebbcole this _is_ the "linter helper", so I'm not sure what you are talking about there. If you are saying those issues are problems with how this provider is currently written then can you fix those errors so the users of this no longer need to file issues on it?

As I said in the post, the templating languages range from "looks to be valid" to "`htmlhint` isn't smart enough to see they aren't", but I can put those back in, you need to know that they can break in the future and should be broken right now.

As the linked issue states, this is already broken for Handlebars, and you should probably be using [linter-handlebars](https://atom.io/packages/linter-handlebars) for that...

**Comment by johnwebbcole** [comment]
If there is a specific linter that supersedes htmlhint, then htmlhint should not include that scope.  So if there is one for handlebars, then it should be removed from the scope.  Keep in mind that adding handlebars was specifically requested.

Looks like erb has a specific linter now too.  

The others seem to work ok, while some need a rule or two disabled (but the other rules run fine), which is easily handled with a .htmlhintrc file.

This is a linter plugin, not a helper.  There is a linter helper library that this plugin uses.  When the main linter gets updated, there have been problems in the past with that helper library.  I've found that waiting a few days to make sure the library changes are stable helps a great deal.  Many issues reported are resolved on the next linter update, as the same pattern is used by other plugins and they break in a similar way.

Scopes that need one rule disabled should not be removed.  A documentation note suggesting a .htmlhintrc setting would be nice though.  If there is a linter for that type, we should remove it from the scopes and let the other linter plugin work, if not htmlhint works pretty well still.

**Comment by Arcanemagus** [comment]
I just looked through the issues and not a single one was related to `atom-linter` (the helper package I'm assuming you are talking about), other than one that was an _Atom_ bug related to profile paths with non-ASCII characters.

As explained in #44 disabling that rule isn't really a solution as that disables it for the entire file. This linter was never designed to handle templated files.

It looks like you added all these extra scopes in https://github.com/AtomLinter/linter-htmlhint/commit/3715c5dcd55ada62807235013262fa986ad54159 in order to "fix" #26, which you never really got confirmation that that was even the issue for.

I'll take out the removal of Mustache and Angular, but I really don't see how the other scopes should be kept.

**Comment by Arcanemagus** [comment]
The entire point of this PR is that quite a few of the issues currently open on this provider are due to it attempting to lint files it shouldn't be, and the issues were not being handled.

**Comment by johnwebbcole** [comment]
We should only remove scopes if there is an alternative linter available.  Otherwise, leave them in, and users can configure the rules with .htmlhintrc files and loose partial functionally, not all of it.  The only other linter available is linter-tidy, and I think that htmlhint works much better than tidy, and is much more configurable.

**Comment by johnwebbcole** [comment]
A better way to do this would be to enumerate the text.html.* scopes and provide options to disable them.

**Comment by Arcanemagus** [comment]
That works well enough, it can be done similar to how `linter-eslint` does it. I'll see if I have some time to implement that unless you want to.

**Comment by johnwebbcole** [comment]
Is there a way to git a list of all of the text.html.* scopes?

**Comment by Arcanemagus** [comment]
I would only list the ones requested so far... but in any case this is the only list I know of: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

**Comment by Arcanemagus** [comment]
Closing this, there doesn't seem to be too much interest in it, and the large number of incoming issues seems to have died off anyway.

**Pull request closed without merging**
